[project]
name = "shenzhen-shared-bike-analysis"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "aiohttp>=3.12.15",
    "loguru>=0.7.3",
    "pandas>=2.3.2",
    "requests>=2.32.3",
    "psycopg[binary]>=3.2.9",
    "pydantic>=2.11.7",
    "pydantic-settings>=2.10.1",
    "tqdm>=4.67.1",
    "eviltransform>=0.1.1",
    "geopandas>=1.1.1",
    "shapely>=2.1.1",
]

[[tool.uv.index]]
url = "https://pypi.tuna.tsinghua.edu.cn/simple"
default = true

[dependency-groups]
dev = [
    "notebook>=7.4.5",
    "pyogrio>=0.11.1",
    "pyproj>=3.7.2",
]
